### ISSUE TITLE
Changing map to recoveries

### ISSUE THREAD

**Issue by ojsimon** [ExpDev07/coronavirus-tracker#3]
Hi, 

Is there an easy way to change the red circles on the map to represent recoveries instead of deaths?

Thanks

**Comment by ExpDev07** [comment]
Well yes, if you look in ``/templates/index.hbs``, you can see that it passes the confirmed cases to the ``Map`` component. Simply change to
```handlebars
{{!-- The map visualization --}}
<section>
  <Map @data={{@model.deaths.locations}} />
</section>```

**Comment by ExpDev07** [comment]
The framework used is EmberJS Octane. You should probably read about it and learn in the docs instead of asking questions here (I don't mind it, but it's not a very begginer-friendly framework, though it is my favorite 100%, and some things are hard to explain): https://emberjs.com/.

**Comment by ojsimon** [comment]
Thanks so much. Will read the guide about Ember too. Thanks
